### ISSUE TITLE
Question about "Employing GradCAM highlights the focus areas"

### ISSUE THREAD

**Issue by xiaokj37** [amazon-science/QA-ViT#1]
Will you update the code about "Employing GradCAM highlights the focus areas" later?
At the same time, I hope you can open source the training code as soon as possible so that we can follow and learn from it.
Thanks.

**Comment by royg27** [comment]
Hi,

First of all, thanks for your interest in our work. We are currently working on making the training scripts publicly available, and hopefully, it will be available soon!

**Comment by xiaokj37** [comment]
Thanks for your replay. 
In addition to the Training code, I am also interested in using GradCAM for visualization. I want to reproduce the Attention graph shown in your paper and the repository. Is there any plan to open source this part of the code later?

**Comment by royg27** [comment]
Unfortunately, we have implemented this visualization in a standalone notebook, which we cannot publish.
However, we used the standard GradCAM with respect to the text prompts of interest (harnessing on the fact that the ViT is based on CLIP, which has a text encoder)

**Comment by xiaokj37** [comment]
Thank you very much for your reply.
I'm trying to reproduce it by myself.
