### ISSUE TITLE
Can QAVit be applied to multi-turn conversations?

### ISSUE THREAD

**Issue by echo840** [amazon-science/QA-ViT#2]
Thank you for your great work, but I think QA-VIT may have a small flaw. 
For example, with models like LLaVA, in multi-turn conversations, you only need to input the image into CLIP-VIT once. However, with QA-VIT, since the questions in each round of conversation are different, you have to input the image and question into QA-VIT for each round, which can lead to lower training and inference efficiency.
Is my statement reasonable?

**Comment by royg27** [comment]
Hi,
Thanks for your appreciation of our work.

In general, I think that you are right. One can mitigate this by capitalizing on the fact that we incorporate the question embedding into the ViT using late fusion, enabling storing the intermediate representations that are not question-dependent.

Additionally, while we agree that this can be a limitation compared to regular ViT in the multi-turn setting, the image encoding phase is relatively fast compared to the application of the LLM.

**Comment by echo840** [comment]
Thank you for your response and your great work! 
In multi-turn dialogue training, the previous hidden states are stored in past-key-value for later generation. This allows the image to pass through the ViT only once, and the image token only needs to go through the LLM once. However, when using QA-ViT, the image token needs to go through the LLM n times(assuming there are n dialogue turns), and this additional time cannot be reduced.
However, these minor limitations do not detract from the fact that this article is a very good one.
Thank you.
