### ISSUE TITLE
Question about instruct_embeds, image_features, input_embeds

### ISSUE THREAD

**Issue by xiaokj37** [amazon-science/QA-ViT#3]
<img width="855" alt="image" src="https://github.com/amazon-science/QA-ViT/assets/55699998/53ff71f7-a063-441a-bf3b-bf98b76830d1">

This part of the code is part of VisualT5.py, I would like to ask what is the difference between the instruct_embeds in it and the input_embeds at the beginning, it seems that they both represent the user's input.
And then the image_features here is the feature extracted by QA-ViT?
Hope for your early replay.

**Comment by royg27** [comment]
Hi,

First of all, thanks for your interest in our work.
The input_embeds and the instruct_embeds are two different variables that enable different inputs to the ViT and the LLM. For example, it enables formatting the question to the LLM with an instruction template while keeping it intact for the ViT. However, in our configuration, we feed the ViT and the LLM the same inputs, making these variables the same. 
The image_features are indeed the features extracted by the QA-ViT, as you mentioned.

**Comment by xiaokj37** [comment]
Thanks for your reply, I now understand this part.
I would also like to ask, does QA-ViT support multiple questions for one image? For example, “what color is the bear?”, “what color is the bear's nose?” for one image.
That is, can QA-ViT focus on areas related to multiple questions?

**Comment by royg27** [comment]
Sure, you are welcome :)
I may not follow. Do you mean multiple questions that should guide a single answer? For example, "Do you see the bear? What is its nose color?". The model was not trained in this way, and I haven't tested this scenario, but perhaps such textual guidance can work and even improve the performance!

**Comment by xiaokj37** [comment]
Sorry, maybe I didn't express it clearly.
I looked at the code where you deal with the problems in the dataset, and the problems were not considered separately. 
`def pre_question(question,max_ques_words=50):
    question = re.sub(
        r"([.!\"()*#:;~])",
        '',
        question.lower(),
    ) 
    question = question.rstrip(' ')
    
    #truncate question
    question_words = question.split(' ')
    if len(question_words)>max_ques_words:
        question = ' '.join(question_words[:max_ques_words])
            
    return question`
For example, in VizWiz datasets, there are some QA like "Question: What is it? What color is it?"
Does this mean that image_features focuses on both problems together?
What's more, the "max_ques_words" is set to 50, can it be modified to be larger?

**Comment by royg27** [comment]
Thanks for the clarification. We treat the user input as a single stream of information; in this case, the result is that the image features would have to account for both questions simultaneously.
The "max_ques_words" is set to reduce the self-attention layer's computational cost. From our dataset analysis, the chosen size was enough for the vast majority of the inputs. However, you can increase it if needed.

**Comment by xiaokj37** [comment]
Thanks for your reply. According to your reply, if I increase max_ques_words, do I need to retrain QA-ViT?

**Comment by royg27** [comment]
Technically speaking, you can increase the maximal sequence length without retraining. However, perhaps the new style of questions (the long ones), which differs from the ones used for training, might decrease the results.
We plan to release the training script soon, so you can also train it if necessary 😃
