### ISSUE TITLE
Question embedding module for Llava-1.5

### ISSUE THREAD

**Issue by xl1990** [amazon-science/QA-ViT#7]
Hi,

Thank you for your amazing work! I have a question about with which module you process the questions for QA-ViT. In the paper's appendix, it is mentioned that "we use the model’s embedding module to process the questions when applying QA-ViT". Could you please clarify whether "the model’s embedding module" refers specifically to the `nn.Embedding` layer in Llama, or if it involves something else?

P.S. I would be pretty surprised if there is only one layer for extracting the question embeddings as it seem to be very shallow to extract semantic information from the question.

**Comment by royg27** [comment]
Hi 😀

First of all, thank you for your interest and kind words. As for the question embedding in the LLAaVA case, we simply use the embedding layer as you specified. Our experiments indicate that this suffices.

**Comment by showstarpro** [comment]
Can I understand that in LLaVA, for the text embedding of QA-ViT, using a simple `nn.Embedding` is acceptable, and using a CLIP encoder or BERT encoder is also acceptable?
