### ISSUE TITLE
Request for Evaluation Code for CIDEr and VQA-Score

### ISSUE THREAD

**Issue by casperliuliuliu** [amazon-science/QA-ViT#9]
I really appreciate the work you've done. 

I was wondering if you could provide the evaluation code for different scoring methods, such as COCO CIDEr and VQA score. 
I would like to reimplement your experiments. 

Thank you!

**Comment by royg27** [comment]
Hi,

First of all, thanks for your interest and appreciation of our work.
Regarding the metrics we used:
1) For VQAv2 score: We used the official evaluation server on EvalAI.
2) For TextVQA: We used the local evaluation script in this repo.
3) For COCO CIDEr: We used the publicly available pycocoevalcap package.
